version: build-{build}
nuget:
  disable_publish_on_pr: true
build_script:
- build_[CI_Debug]
artifacts:
- path: bin\Releases
  name: Releases
- path: bin\Releases\Bridge_v*
  name: Bridge
- path: bin\Releases\CI.MSBuild_v*
  name: CI.MSBuild
- path: bin\Releases\Devenv_v*
  name: Devenv
- path: bin\Releases\Provider_v*
  name: Provider
- path: bin\Releases\Release_notes.txt
  name: Release_notes
- path: bin\Releases\vsSolutionBuildEvent_v*
  name: vsSolutionBuildEvent
notifications:
- provider: Email
  to:
  - entry.reg@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true